import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,Menu,ChevronRight,ChevronDown,CheckCircle2,AlertTriangle,RotateCcw,Maximize2,HelpCircle,BookOpen,Home,Factory,ShieldCheck,GraduationCap,Activity,Calculator,ArrowLeft,ArrowRight,X,Info,ClipboardCheck,Filter} from 'lucide-react';
import './styles.css';

const img=(q)=>`https://images.unsplash.com/photo-${q}?auto=format&fit=crop&w=1200&q=82`;
const heroImg='https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&w=1600&q=85';

const sections=[
 {title:'PRODUCTION',icon:Activity,items:['Broiler Overview','Breed & Genetics','Hatchery','Day 1 Chick','Brooding','Grow-Out','Feed Management','Water Management','Lighting','Ventilation','Temperature','Stocking Density','Litter Management','Health Monitoring','Biosecurity','Farm Records','Catching & Loading','Transport']},
 {title:'PROCESSING',icon:Factory,items:['Receiving','Pre-Operational Checks','Live Bird Inspection','Slaughter','Bleeding','Scalding','Defeathering','Head Removal','Feet Removal','Evisceration','Carcass Washing','Chilling','Grading','Cutting','Deboning','Packing','Metal Detection','Cold Storage','Dispatch']},
 {title:'ANATOMY',icon:BookOpen,items:['External Anatomy','Skeletal System','Muscular System','Digestive System','Respiratory System','Cardiovascular System','Reproductive System','Immune Organs','Internal Organs','Chicken Cuts']},
 {title:'QUALITY CONTROL',icon:ClipboardCheck,items:['QC Fundamentals','Receiving Inspection','Processing Inspection','Carcass Defects','Bruising','Broken Bones','Wing Damage','Leg Damage','Breast Defects','Feather Retention','Contamination','Evisceration Defects','Chilling Control','Packaging Inspection','Cold Chain']},
 {title:'FOOD SAFETY',icon:ShieldCheck,items:['HACCP','Biological Hazards','Chemical Hazards','Physical Hazards','Cross Contamination','Sanitation','Personal Hygiene','Temperature Control','Traceability','Corrective Actions']},
 {title:'TRAINING',icon:GraduationCap,items:['QC Simulator','Inspection Scenarios','Knowledge Quiz','Process Quiz','Anatomy Quiz','Food Safety Quiz']}
];
const journey=['Breeder & Genetics','Hatchery','Chick Placement','Development','Environment','Feed','Growth Monitoring','Health','Biosecurity','Catching','Transport','Receiving','Pre-Operational Checks','Ante-Mortem','Slaughter','Bleeding','Scalding','Defeathering','Evisceration','Washing','Chilling','Grading','Cutting','Packaging','Storage & Dispatch','Consumer / Cooking'];
const descriptions={
 'Broiler Overview':['A production-focused orientation to modern meat-chicken systems.','Connect genetics, farm management, processing controls and food safety from one flock journey.','Use this atlas as training material alongside plant SOPs and applicable regulations.'],
 'Breed & Genetics':['Commercial broilers are selected for efficient growth, feed conversion, carcass yield and production consistency.','Genetics influence growth curve, breast yield, skeletal robustness and management requirements.'],
 'Hatchery':['Egg handling, incubation, hatch, chick quality and vaccination are key early controls.','Strong chick quality supports uniform placement, early feed and water access, and flock performance.'],
 'Day 1 Chick':['Check activity, hydration, navels, legs, eyes and general uniformity at placement.','Provide immediate access to clean water and feed and establish the correct brooding environment.'],
 'Brooding':['The first days require close control of chick comfort, temperature, litter condition, ventilation and access to resources.'],
 'Grow-Out':['Monitor body weight, uniformity, feed intake, water intake, mortality and flock behavior against the farm program.'],
 'Feed Management':['Starter → Grower → Finisher programs are designed around changing nutrient and growth needs.','Actual specifications depend on genetics, formulation, climate, production objective and local program.'],
 'Water Management':['Reliable water access is essential. Monitor drinker function, pressure/height, cleanliness, quality and flock consumption trends.'],
 'Lighting':['Lighting programs influence activity, feeding behavior, rest and flock management. Follow the approved farm lighting program.'],
 'Ventilation':['Ventilation supplies oxygen, removes heat and moisture, and helps control gases and litter condition.'],
 'Temperature':['Bird comfort depends on age, humidity, air speed, stocking, equipment and bird behavior—not temperature alone.'],
 'Stocking Density':['Use house area and bird count to calculate birds/m². Regulatory or welfare limits vary by jurisdiction and program.'],
 'Litter Management':['Dry, friable litter supports bird welfare and reduces moisture-related problems. Identify wet or caked areas early and investigate causes.'],
 'Health Monitoring':['Observe flock behavior, feed/water intake, mortality, respiratory signs, fecal changes and other abnormalities; escalate according to veterinary procedures.'],
 'Biosecurity':['Control people, vehicles, equipment, pests, movement and sanitation to reduce introduction and spread of hazards.'],
 'Farm Records':['Good records link flock identity to feed, medication/vaccination, mortality, weights, environmental data and movement.'],
 'Catching & Loading':['Gentle, controlled catching and appropriate loading practices reduce stress and injury. Follow approved welfare procedures.'],
 'Transport':['Crate condition, loading density, ventilation, weather, journey time and handling affect bird welfare and receiving condition.'],
 'Receiving':['Record flock identity, arrival time, condition, DOA, documentation and other plant-defined receiving observations.'],
 'Pre-Operational Checks':['Verify sanitation, equipment condition, water/ice/chiller readiness, chemicals, instruments, metal detection, PPE and documentation before production.'],
 'Live Bird Inspection':['Observe live birds for condition, welfare concerns, abnormalities and segregation needs; escalate veterinary concerns.'],
 'Slaughter':['A controlled slaughter process must protect welfare, product identity and food safety. Follow plant procedures and applicable law.'],
 'Bleeding':['Bleeding performance affects carcass appearance and downstream quality. Investigate inadequate bleeding with the responsible process team.'],
 'Scalding':['Scalding loosens feathers for removal. Time, temperature and equipment performance are process variables that must be controlled by the plant program.'],
 'Defeathering':['Machine setup, maintenance and process conditions influence feather removal, skin damage and bruising.'],
 'Head Removal':['Controlled removal protects carcass integrity and supports clean downstream processing.'],
 'Feet Removal':['Feet removal must be controlled to avoid unnecessary carcass damage and contamination transfer.'],
 'Evisceration':['A critical quality and hygiene step: remove viscera while protecting the gastrointestinal tract and carcass integrity. Inspect for contamination, retained viscera and tears.'],
 'Carcass Washing':['Washing is part of the plant’s validated hygiene system. It does not replace good process control or sanitation.'],
 'Chilling':['Rapid, controlled chilling reduces product temperature and supports shelf life and food safety. Verify against plant and regulatory requirements.'],
 'Grading':['Grade carcasses by the plant’s approved criteria for weight, defects, trim and product specification.'],
 'Cutting':['Cutting converts whole carcasses into market portions. Control yield, specification, bone damage, trim and product identity.'],
 'Deboning':['Deboning separates muscle from bone while managing yield, contamination risks and product integrity.'],
 'Packing':['Match product, packaging, weight, label, lot/batch identity and inspection requirements.'],
 'Metal Detection':['Use validated challenge procedures and plant-defined controls. Treat failures as deviations requiring documented response.'],
 'Cold Storage':['Maintain product identity, stock rotation and the cold chain. FIFO/FEFO logic depends on the product/date system used by the facility.'],
 'Dispatch':['Pick the correct batch, verify documentation, vehicle hygiene and cold-chain controls before dispatch.'],
 'External Anatomy':['Identify the main external structures used in husbandry, inspection and processing.'],
 'Skeletal System':['The skeleton provides support and is important to gait, handling, processing yield and defect assessment.'],
 'Muscular System':['Breast and leg muscles are major commercial tissues; growth, activity and processing affect their appearance and quality.'],
 'Digestive System':['Crop, esophagus, proventriculus, gizzard, intestines, ceca, liver and cloaca form a connected digestive system.'],
 'Respiratory System':['Trachea, lungs and air sacs form a specialized avian respiratory system. Abnormal observations may require veterinary assessment.'],
 'Cardiovascular System':['The heart and vascular system distribute oxygen and nutrients and support thermoregulation and metabolism.'],
 'Reproductive System':['Male and female reproductive structures differ; this module focuses on basic anatomy rather than breeding procedures.'],
 'Immune Organs':['Bursa of Fabricius, thymus, spleen and other lymphoid tissues support immune function.'],
 'Internal Organs':['Use the organ explorer to review location, function and processing relevance.'],
 'Chicken Cuts':['Explore common commercial cuts and the QC checkpoints associated with portioning.'],
 'QC Fundamentals':['QC combines specification checks, observations, measurements, records, escalation and corrective action.'],
 'Receiving Inspection':['Confirm flock identity, condition, DOA observations, documentation and receiving criteria.'],
 'Processing Inspection':['Inspect process-specific risks at defined points and document deviations consistently.'],
 'Carcass Defects':['Differentiate physiological variation, injury, processing damage and contamination before deciding on disposition.'],
 'Bruising':['Bruising is discoloration associated with tissue damage. Consider timing, handling, equipment and welfare when investigating trends.'],
 'Broken Bones':['Assess location, severity and product impact. Trend recurring damage back to catching, transport or processing equipment.'],
 'Wing Damage':['Look for bruising, fractures, dislocation or tears and connect findings to handling/process stages.'],
 'Leg Damage':['Review bruising, fractures, dislocation and hock/footpad findings using the farm-to-plant trend.'],
 'Breast Defects':['Review bruising, skin damage, discoloration and other specification defects.'],
 'Feather Retention':['Residual feathers can indicate scalding or defeathering performance issues and should be trended.'],
 'Contamination':['Separate contamination from normal anatomy or process defects. Follow plant food-safety procedures and disposition rules.'],
 'Evisceration Defects':['Common inspection points include contamination, retained viscera, intestinal rupture, organ damage and carcass tears.'],
 'Chilling Control':['Verify chilling performance using calibrated measurements and the facility’s defined requirements.'],
 'Packaging Inspection':['Check seal integrity, label accuracy, net weight, traceability and package condition.'],
 'Cold Chain':['Monitor product temperature, room conditions, dwell time, loading and transport continuity using approved limits.'],
 'HACCP':['HACCP identifies hazards, establishes preventive controls, monitoring, corrective action, verification and records.'],
 'Biological Hazards':['Biological hazards may include pathogenic microorganisms. Control them through validated food-safety systems, sanitation, process controls and verification.'],
 'Chemical Hazards':['Control cleaning chemicals, lubricants, residues and other chemical risks through approved materials, storage, use and verification.'],
 'Physical Hazards':['Foreign materials such as metal, plastic, glass or stones require prevention, detection and corrective action.'],
 'Cross Contamination':['Prevent transfer through zoning, hygiene, equipment controls, handwashing, sanitation and process flow.'],
 'Sanitation':['Effective sanitation combines pre-operational cleaning, inspection, chemicals, contact time, water quality and verification.'],
 'Personal Hygiene':['Handwashing, protective clothing, illness reporting, controlled movement and hygienic behavior are core controls.'],
 'Temperature Control':['Use calibrated instruments and plant/regulatory criteria to control temperature through processing, storage and dispatch.'],
 'Traceability':['Traceability links raw material, flock/batch, processing records, packaging identity and distribution.'],
 'Corrective Actions':['A strong corrective action addresses immediate product control, root cause, disposition, verification and prevention of recurrence.']
};
const anatomy=[['Heart','Cardiovascular','Pumps blood through the circulation.','Inspect for abnormalities during viscera examination.'],['Liver','Digestive / metabolic','Large organ involved in metabolism and bile production.','Check appearance and integrity when handled as a giblet.'],['Gizzard','Digestive','Muscular stomach that mechanically processes feed.','Common giblet; inspect for damage, contamination and correct processing.'],['Proventriculus','Digestive','Glandular stomach that secretes digestive fluids.','Located before the gizzard; relevant during evisceration.'],['Crop','Digestive','Expandable storage area of the esophagus.','Should be considered during evisceration and feed-withdrawal management.'],['Esophagus','Digestive','Tube carrying ingesta toward the stomach.','Protect integrity during evisceration.'],['Intestines','Digestive','Major site of digestion and nutrient absorption.','Rupture can create contamination risk.'],['Ceca','Digestive','Paired blind pouches connected to the intestine.','Anatomical reference during evisceration.'],['Spleen','Immune','Lymphoid organ involved in immune and blood functions.','Abnormal findings may require escalation.'],['Kidneys','Urinary','Paired organs involved in waste excretion and fluid balance.','Located dorsally along the spine.'],['Lungs','Respiratory','Compact avian lungs involved in gas exchange.','Respiratory abnormalities can be relevant to veterinary review.'],['Trachea','Respiratory','Airway from laryngeal region toward the lungs.','Inspect when respiratory abnormalities are suspected.'],['Air sacs','Respiratory','Thin-walled structures supporting avian respiratory ventilation.','Notable in anatomy and some disease observations.'],['Bursa of Fabricius','Immune','Lymphoid organ associated with B-cell development in young birds.','Age-dependent structure; abnormalities may have veterinary relevance.'],['Cloaca','Digestive / urogenital','Common terminal chamber for digestive and urogenital tracts.','Important reference point in processing hygiene.']];
const cuts=['Whole bird','Breast','Breast fillet','Tenderloin','Thigh','Drumstick','Leg quarter','Wing','Drumette','Wingette','Wing tip','Back','Neck','Giblets','Liver','Heart','Gizzard'];
const defects=['Bruising','Broken bone','Skin tear','Residual feathers','Contamination','Excessive trimming','Wing damage','Leg damage','Breast discoloration','Hock burn','Footpad lesion','Neck damage','Scalding damage','Defeathering damage','Evisceration damage','Intestinal rupture','Carcass tearing'];
const glossary=[['Ante-mortem','Inspection or observation of live animals before slaughter.'],['Biosecurity','Measures that reduce introduction and spread of biological hazards between people, animals and sites.'],['Brooding','Early-life management of chicks with controlled environmental conditions.'],['Carcass','The dressed body after slaughter and specified processing steps.'],['Chilling','Controlled reduction of product temperature after processing.'],['Defeathering','Mechanical removal of feathers after scalding.'],['Evisceration','Removal of internal viscera from the carcass.'],['FCR','Feed conversion ratio: feed consumed divided by live weight gain.'],['HACCP','Hazard Analysis and Critical Control Point system.'],['Halal','A set of Islamic dietary requirements; slaughter requirements vary by applicable authority and certification system.'],['Litter','Material used on the poultry-house floor to absorb moisture and support bird comfort.'],['DOA','Dead on arrival: a bird that arrives at the processing facility already dead.'],['QC','Quality control: operational checks used to meet product and process specifications.'],['CCP','Critical control point within a HACCP system.'],['Cold Chain','Continuous temperature-controlled handling from processing/storage through distribution.'],['Traceability','Ability to follow product and process history through linked records.']];
const quizzes={
 'Knowledge Quiz':[
  ['Which formula calculates FCR?',['Feed consumed ÷ live weight gain','Live weight gain ÷ feed consumed','Bird count ÷ house area','Mortality ÷ feed intake'],0,'FCR is feed consumed divided by live weight gain.'],
  ['Which is a physical hazard?',['Salmonella','Cleaning chemical','Metal fragment','Excess moisture'],2,'Metal fragments are physical hazards.'],
  ['What is the main purpose of chilling?',['Increase carcass weight','Reduce product temperature','Remove all microbes','Improve feather growth'],1,'Chilling rapidly reduces product temperature and supports the cold chain.'],
  ['What should a failed pre-op check trigger?',['Ignore it if production is busy','Document and follow corrective-action procedure','Change the product label','Increase stocking density'],1,'A failure should be controlled, documented and corrected according to the plant system.'],
  ['What is traceability used for?',['Decoration','Linking product to its history and records','Increasing bird growth','Measuring room humidity'],1,'Traceability connects product identity with source, process and distribution records.']
 ],
 'Process Quiz':[
  ['Which stage follows defeathering?',['Evisceration','Hatchery','Farm placement','Retail'],0,'In the simplified processing flow, evisceration follows defeathering/head/feet removal.'],
  ['What can residual feathers indicate?',['A possible scalding/defeathering issue','Only a packaging issue','Always disease','Always normal anatomy'],0,'Feather retention can be trended to scalding and defeathering performance.'],
  ['Which step converts whole carcasses into portions?',['Cutting','Receiving','Bleeding','Dispatch'],0,'Cutting creates commercial portions.']
 ],
 'Anatomy Quiz':[
  ['Which organ is the muscular stomach?',['Liver','Gizzard','Spleen','Lung'],1,'The gizzard is the muscular stomach.'],
  ['Where is the bursa of Fabricius primarily associated?',['Immune function','Feather removal','Feed mixing','Chilling'],0,'It is a lymphoid organ associated with B-cell development in young birds.'],
  ['Which structure is part of the respiratory system?',['Ceca','Trachea','Gizzard','Cloaca'],1,'The trachea is an airway in the respiratory system.']
 ],
 'Food Safety Quiz':[
  ['Which is a biological hazard?',['Metal','Pathogenic microorganism','Plastic','Detergent'],1,'Pathogenic microorganisms are biological hazards.'],
  ['What is the best approach to cross-contamination?',['Rely only on final inspection','Prevent transfer using hygiene, zoning and process controls','Mix raw and ready-to-eat tools','Skip sanitation verification'],1,'Prevention through hygienic design and controlled movement is fundamental.'],
  ['What should calibrated instruments support?',['Reliable measurements','Marketing claims only','Staff attendance','Breed selection'],0,'Calibration supports confidence in process measurements.']
 ]
};
const scenarios=Array.from({length:15},(_,i)=>({id:i+1,title:`QC Scenario ${i+1}`,stage:['Evisceration','Receiving','Defeathering','Chilling','Packing'][i%5],question:['A carcass has visible intestinal material after evisceration. What is the primary concern?','Several birds arrive with abnormal condition and elevated DOA observations. What should you do first?','Many carcasses show residual feathers after defeathering. What is the most useful next action?','Product temperature readings are outside the plant-defined specification. What is the immediate QC priority?','A tray label does not match the product identity. What is the primary concern?'][i%5],options:[['Normal carcass','Potential contamination','Normal feathering','Normal anatomical variation'],['Ignore it','Document receiving deviation and escalate per procedure','Send directly to packing','Change flock identity'],['Investigate scalding/defeathering settings and equipment','Increase label size','Skip inspection','Change bird breed'],['Control affected product and follow deviation/corrective-action procedure','Release immediately','Remove labels','Increase stocking density'],['Traceability/product identity failure','Normal variation','Anatomy issue','Farm genetics']][i%5],correct:[1,1,0,0,0][i%5],explanation:['Visible intestinal material indicates a contamination concern requiring product control and investigation.','Receiving abnormalities should be documented and escalated according to plant/veterinary procedures.','Trend residual feathers back to scalding and defeathering process performance.','Control affected product and follow the approved deviation process and temperature requirements.','Incorrect product identity can break traceability and requires immediate control.'][i%5]}));

function useHash(){const [page,setPage]=useState(location.hash.slice(1)||'home');useEffect(()=>{const f=()=>setPage(location.hash.slice(1)||'home');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);return [page,p=>{location.hash=p}]}
function App(){const [page,setPage]=useHash();const [open,setOpen]=useState(true);const [search,setSearch]=useState('');const [fullscreen,setFullscreen]=useState(false);const [progress,setProgress]=useState(()=>JSON.parse(localStorage.getItem('bca-progress')||'{}'));useEffect(()=>localStorage.setItem('bca-progress',JSON.stringify(progress)),[progress]);const all=[...sections.flatMap(s=>s.items),...journey,'Home','The Broiler Journey','Stocking Density Calculator','FCR Calculator','Glossary','Sources & References','Damage Atlas','Disease & Abnormality Atlas'];const results=useMemo(()=>all.filter(x=>x.toLowerCase().includes(search.toLowerCase())).slice(0,10),[search]);const go=x=>setPage(x==='Home'?'home':x.toLowerCase().replaceAll(' ','-').replaceAll('/','-'));const mark=x=>setProgress(p=>({...p,[x]:true}));return <div className={fullscreen?'app fullscreen':'app'}><header><button className="iconBtn mobileOnly" onClick={()=>setOpen(!open)}><Menu size={21}/></button><div className="brand"><div className="brandMark">BCA</div><div><b>Broiler Chicken Atlas</b><span>Production • Processing • QC • Food Safety</span></div></div><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search anatomy, process, defect, QC term…"/>{search&&<button onClick={()=>setSearch('')}><X size={16}/></button>}{search&&results.length>0&&<div className="searchDrop">{results.map(r=><button key={r} onClick={()=>{go(r);setSearch('')}}><span>{r}</span><ChevronRight size={15}/></button>)}</div>}</div><div className="headerActions"><button title="Help"><HelpCircle size={19}/></button><button title="Progress" onClick={()=>go('progress')}><Activity size={19}/><span className="desktopOnly">Progress</span></button><button title="Fullscreen" onClick={()=>setFullscreen(!fullscreen)}><Maximize2 size={18}/></button></div></header><div className="layout"><aside className={open?'sidebar':'sidebar collapsed'}><div className="sideTop"><button className="collapse" onClick={()=>setOpen(!open)}><Menu size={19}/></button><span>ATLAS NAVIGATION</span></div>{sections.map(s=><div className="navSection" key={s.title}><div className="navLabel">{React.createElement(s.icon,{size:16})}<span>{s.title}</span></div>{open&&s.items.map((x,i)=><button className={page===x.toLowerCase().replaceAll(' ','-')?'navItem active':'navItem'} key={x} onClick={()=>go(x)}><span className="num">{sections.slice(0,sections.indexOf(s)).reduce((a,z)=>a+z.items.length,0)+i+1}</span>{x}</button>)}</div>)}</aside><main><Page page={page} go={go} mark={mark} progress={progress}/></main></div><nav className="bottomNav"><button onClick={()=>go('home')}><Home size={19}/>Home</button><button onClick={()=>go('the-broiler-journey')}><Activity size={19}/>Journey</button><button onClick={()=>go('qc-simulator')}><ClipboardCheck size={19}/>QC</button><button onClick={()=>go('knowledge-quiz')}><GraduationCap size={19}/>Train</button></nav></div>}

function Page({page,go,mark,progress}){const title=page==='home'?'Home':page.split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');if(page==='home')return <HomePage go={go} progress={progress}/>;if(page==='the-broiler-journey')return <Journey go={go} mark={mark}/>;if(page==='pre-operational-checks')return <PreOp mark={mark} progress={progress}/>;if(page==='qc-simulator')return <QCSimulator/>;if(page==='inspection-scenarios')return <Scenarios/>;if(['knowledge-quiz','process-quiz','anatomy-quiz','food-safety-quiz'].includes(page))return <Quiz name={title}/>;if(page==='stocking-density')return <Stocking/>;if(page==='fcr-calculator')return <FCR/>;if(page==='glossary')return <Glossary/>;if(page==='sources-&-references')return <Sources/>;if(page==='damage-atlas')return <DamageAtlas/>;if(page==='disease-&-abnormality-atlas')return <DiseaseAtlas/>;if(page==='progress')return <Progress progress={progress}/>;if(['external-anatomy','skeletal-system','muscular-system','digestive-system','respiratory-system','cardiovascular-system','reproductive-system','immune-organs','internal-organs','chicken-cuts'].includes(page))return <Anatomy page={title}/>;return <Module title={title} go={go}/>}

function Crumb({items=[]}){return <div className="crumb">Atlas <ChevronRight size={14}/>{items.map((x,i)=><React.Fragment key={x}><span>{x}</span>{i<items.length-1&&<ChevronRight size={14}/>}</React.Fragment>)}</div>}
function HomePage({go,progress}){return <div className="content"><Crumb items={['Home']}/><section className="hero"><div className="heroCopy"><span className="eyebrow">PROFESSIONAL TRAINING & REFERENCE</span><h1>Broiler Chicken<br/><em>Atlas</em></h1><p>From Farm to Fork — production, processing, anatomy, quality control and food safety in one interactive reference platform.</p><div className="heroBtns"><button className="primary" onClick={()=>go('the-broiler-journey')}>Explore the Journey <ArrowRight size={17}/></button><button className="secondary" onClick={()=>go('knowledge-quiz')}>Start Training <GraduationCap size={17}/></button></div></div><div className="heroVisual"><img src={heroImg} alt="Broiler chicken in a farm setting"/><div className="imageCaption">Broiler production • farm-to-fork learning</div></div></section><section className="journeyIntro"><div><span className="eyebrow">INTERACTIVE PROCESS MAP</span><h2>Explore the Broiler Journey</h2><p>Follow the complete production and processing chain. Select any stage for practical learning points, QC relevance and process controls.</p></div><button className="textBtn" onClick={()=>go('the-broiler-journey')}>Open full atlas <ArrowRight size={16}/></button></section><div className="journeyRail">{['Hatchery','Farm','Catching','Transport','Processing','Chilling','Cutting','Packing','Storage','Dispatch','Consumer'].map((x,i)=><button key={x} onClick={()=>go(journey[Math.min(i*2,journey.length-1)])}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b>{i<10&&<ChevronRight size={17}/>}</button>)}</div><section className="dashboardGrid"><Feature title="Production" icon={Activity} text="Farm setup, growth, feed, water, environment, health and biosecurity." onClick={()=>go('grow-out')}/><Feature title="Processing" icon={Factory} text="Interactive line from receiving through dispatch with process controls." onClick={()=>go('receiving')}/><Feature title="Quality Control" icon={ClipboardCheck} text="Inspection points, damage atlas, scenarios and corrective-action thinking." onClick={()=>go('qc-fundamentals')}/><Feature title="Food Safety" icon={ShieldCheck} text="HACCP, hazards, sanitation, hygiene, temperature and traceability." onClick={()=>go('haccp')}/></section><section className="stats"><div><b>78</b><span>Training modules</span></div><div><b>26</b><span>Journey stages</span></div><div><b>15</b><span>QC scenarios</span></div><div><b>{Object.keys(progress).length}</b><span>Completed items</span></div></section></div>}
function Feature({title,icon:Icon,text,onClick}){return <button className="feature" onClick={onClick}><div className="featureIcon"><Icon size={20}/></div><div><h3>{title}</h3><p>{text}</p></div><ChevronRight size={18}/></button>}
function Journey({go,mark}){return <div className="content"><Crumb items={['The Broiler Journey']}/><PageHead eyebrow="A–Z JOURNEY" title="The Broiler Journey" text="A structured farm-to-fork timeline. Each stage links operational context to QC, welfare and food-safety thinking."/><div className="timeline">{journey.map((x,i)=><button className="timeItem" key={x} onClick={()=>{mark(x);go(x)}}><span className="timeDot">{String.fromCharCode(65+i)}</span><div><b>{x}</b><p>{descriptions[x]?.[0]||'Explore this stage of the broiler journey.'}</p></div><ChevronRight size={18}/></button>)}</div></div>}
function PageHead({eyebrow,title,text,action}){return <div className="pageHead"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Module({title,go}){const d=descriptions[title]||['This module provides a structured professional overview.','Use the information with your facility SOPs, approved specifications and applicable regulations.'];const related=journey.filter(x=>x.toLowerCase().includes(title.toLowerCase().split(' ')[0])).slice(0,3);return <div className="content"><Crumb items={[title]}/><PageHead eyebrow="ATLAS MODULE" title={title} text={d[0]}/><div className="moduleGrid"><article className="articleCard"><div className="illustration"><div className="illustrationIcon"><Info size={28}/></div><span>Scientific learning visual</span><b>{title}</b></div>{d.slice(1).map((p,i)=><section className="textSection" key={i}><h2>{['Core concept','Operational focus','QC / food-safety relevance'][i]||'Key point'}</h2><p>{p}</p></section>)}<Callout title="Professional note">Requirements vary by jurisdiction. Verify applicable local regulation, plant procedures and validated process specifications before using a value as an operational limit.</Callout></article><aside className="infoPanel"><h3>Quick reference</h3><div className="mini"><span>Category</span><b>{title.includes('QC')||title.includes('Defect')?'Quality Control':title.includes('Temperature')||title.includes('HACCP')?'Food Safety':'Production / Processing'}</b></div><div className="mini"><span>Use with</span><b>Plant SOPs + approved specifications</b></div><div className="mini"><span>Training mode</span><b>Review → Observe → Record → Escalate</b></div><button className="wideBtn" onClick={()=>go('inspection-scenarios')}>Practice a scenario <ArrowRight size={16}/></button></aside></div></div>}
function Callout({title,children,type='info'}){return <div className={'callout '+type}><Info size={19}/><div><b>{title}</b><p>{children}</p></div></div>}
function PreOp({mark,progress}){const items=['Food-contact surfaces clean?','Equipment clean and in good condition?','Water system functioning?','Ice / chiller ready?','Sanitizer concentration verified?','Temperature instruments verified?','Metal detector functioning / challenge status checked?','Packaging materials available and correct?','PPE and handwashing compliance?','Pest control / entry controls acceptable?','Required records and forms available?'];const [vals,setVals]=useState(()=>JSON.parse(localStorage.getItem('bca-preop')||'{}'));useEffect(()=>localStorage.setItem('bca-preop',JSON.stringify(vals)),[vals]);const done=Object.values(vals).filter(x=>x&&x!=='N/A').length;const fails=Object.values(vals).filter(x=>x==='FAIL').length;return <div className="content"><Crumb items={['Pre-Operational Checks']}/><PageHead eyebrow="REAL INTERACTIVE TOOL" title="Pre-Operational Checks" text="Complete the simulated pre-op inspection. PASS / FAIL / N/A status is saved locally on this device."/><div className="toolBar"><div><b>{Math.round(done/items.length*100)}%</b><span>completed</span></div><div><b>{fails}</b><span>failed items</span></div><button onClick={()=>{setVals({});localStorage.removeItem('bca-preop')}}><RotateCcw size={16}/>Reset Checklist</button></div><div className="checklist">{items.map((x,i)=><div className="checkRow" key={x}><div><span className="checkNum">{i+1}</span><b>{x}</b></div><div className="choices">{['PASS','FAIL','N/A'].map(v=><button className={vals[i]===v?'selected '+v.toLowerCase():''} key={v} onClick={()=>{setVals({...vals,[i]:v});mark('Pre-Op '+i)}}>{v}</button>)}</div></div>)}</div>{fails>0&&<Callout title="Corrective action prompt" type="warn">Control the affected area/equipment or product as applicable, document the failure, correct the condition, and verify effectiveness before release according to plant procedure.</Callout>}</div>}
function QCSimulator(){const [stage,setStage]=useState('Evisceration');const points={Receiving:['Flock identity','Bird condition / DOA','Documentation'],Evisceration:['Contamination','Retained viscera','Intestinal rupture','Carcass tearing'],Defeathering:['Residual feathers','Skin damage','Bruising'],Chilling:['Product temperature','Chiller performance','Record integrity'],Packing:['Label identity','Seal integrity','Net weight','Traceability']};return <div className="content"><Crumb items={['QC Simulator']}/><PageHead eyebrow="INTERACTIVE QC" title="QC Inspection Simulator" text="Choose a process stage and classify observations. This is training data, not a regulatory acceptance table."/><div className="tabs">{Object.keys(points).map(x=><button className={stage===x?'active':''} onClick={()=>setStage(x)} key={x}>{x}</button>)}</div><div className="inspectionGrid">{points[stage].map((p,i)=><div className="inspectionCard" key={p}><div className="fakePhoto"><span>{stage.toUpperCase()}</span><b>Inspection point {i+1}</b></div><h3>{p}</h3><div className="severity"><button>Normal</button><button>Minor defect</button><button>Major defect</button><button>Critical concern</button></div><p>Record the observation objectively, identify the process stage, control affected product where required, and escalate according to the approved procedure.</p></div>)}</div></div>}
function Scenarios(){const [n,setN]=useState(0);const [ans,setAns]=useState(null);const s=scenarios[n];return <div className="content"><Crumb items={['Inspection Scenarios']}/><PageHead eyebrow="SCENARIO TRAINING" title="QC Inspection Scenarios" text="Fifteen short situations designed to practice observation, product control and escalation thinking."/><div className="scenario"><div className="scenarioTop"><span>Scenario {n+1} / {scenarios.length}</span><b>{s.stage}</b></div><h2>{s.title}</h2><p className="scenarioQ">{s.question}</p><div className="scenarioOptions">{s.options.map((o,i)=><button className={ans!==null?(i===s.correct?'correct':i===ans?'wrong':'') : ''} disabled={ans!==null} onClick={()=>setAns(i)} key={o}>{String.fromCharCode(65+i)}. {o}</button>)}</div>{ans!==null&&<Callout title={ans===s.correct?'Correct':'Review this decision'} type={ans===s.correct?'success':'warn'}>{s.explanation}</Callout>}<div className="scenarioNav"><button disabled={n===0} onClick={()=>{setN(n-1);setAns(null)}}><ArrowLeft size={16}/>Previous</button><button disabled={n===scenarios.length-1} onClick={()=>{setN(n+1);setAns(null)}}>Next<ArrowRight size={16}/></button></div></div></div>}
function Quiz({name}){const qs=quizzes[name]||quizzes['Knowledge Quiz'];const [n,setN]=useState(0),[ans,setAns]=useState(null),[score,setScore]=useState(0);const q=qs[n];const reset=()=>{setN(0);setAns(null);setScore(0)};return <div className="content"><Crumb items={[name]}/><PageHead eyebrow="REAL QUIZ ENGINE" title={name} text="Answer, review the explanation, then continue. Your score is calculated in this session."/><div className="quiz"><div className="quizProgress"><span>Question {n+1} of {qs.length}</span><b>{score} correct</b></div><h2>{q[0]}</h2><div className="quizOptions">{q[1].map((o,i)=><button key={o} disabled={ans!==null} className={ans!==null?(i===q[2]?'correct':i===ans?'wrong':''):''} onClick={()=>{setAns(i);if(i===q[2])setScore(score+1)}}>{String.fromCharCode(65+i)} {o}</button>)}</div>{ans!==null&&<Callout title={ans===q[2]?'Correct':'Not quite'} type={ans===q[2]?'success':'warn'}>{q[3]}</Callout>}<div className="scenarioNav">{n===qs.length-1?<button className="primary" onClick={reset}>Retry Quiz <RotateCcw size={16}/></button>:<button className="primary" disabled={ans===null} onClick={()=>{setN(n+1);setAns(null)}}>Next Question <ArrowRight size={16}/></button>}</div></div></div>}
function Stocking(){const [area,setArea]=useState(''),[birds,setBirds]=useState('');const result=area&&birds?(Number(birds)/Number(area)).toFixed(2):'—';return <Tool title="Stocking Density Calculator" formula="birds/m² = bird count ÷ usable house area (m²)"><label>House area (m²)<input type="number" value={area} onChange={e=>setArea(e.target.value)} /></label><label>Bird count<input type="number" value={birds} onChange={e=>setBirds(e.target.value)} /></label><div className="result"><span>Calculated density</span><b>{result} <small>birds/m²</small></b></div><Callout title="Reference note">This calculator performs the arithmetic only. Welfare, stocking-density and regulatory requirements vary by jurisdiction, bird age/weight and production program.</Callout></Tool>}
function FCR(){const [feed,setFeed]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState('');const gain=Number(end)-Number(start);const result=feed&&gain>0?(Number(feed)/gain).toFixed(3):'—';return <Tool title="FCR Calculator" formula="FCR = Feed Consumed ÷ Live Weight Gain"><label>Feed consumed (kg)<input type="number" value={feed} onChange={e=>setFeed(e.target.value)}/></label><label>Starting live weight (kg)<input type="number" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Ending live weight (kg)<input type="number" value={end} onChange={e=>setEnd(e.target.value)}/></label><div className="result"><span>Calculated FCR</span><b>{result}</b></div></Tool>}
function Tool({title,formula,children}){return <div className="content"><Crumb items={[title]}/><PageHead eyebrow="INTERACTIVE CALCULATOR" title={title} text="Enter your values to calculate a simple management metric."/><div className="toolCard"><div className="formula"><Calculator size={20}/><b>{formula}</b></div><div className="inputs">{children}</div></div></div>}
function Anatomy({page}){const isCuts=page==='Chicken Cuts';const data=isCuts?cuts.map(x=>[x,'Commercial cut','Market portion used in food preparation.','Review cut specification, bone/trim and package identity.']):anatomy;const [sel,setSel]=useState(data[0]);return <div className="content"><Crumb items={['Anatomy',page]}/><PageHead eyebrow="2D SCIENTIFIC EXPLORER" title={page} text="Tap a structure to review its name, location/function and processing relevance. Illustrations are represented as clean schematic panels in this offline-first build."/><div className="anatomyGrid"><div className="organMap">{data.map(x=><button className={sel[0]===x[0]?'selected':''} onClick={()=>setSel(x)} key={x[0]}><span className="organDot">{x[0][0]}</span><div><b>{x[0]}</b><small>{x[1]}</small></div><ChevronRight size={16}/></button>)}</div><article className="organDetail"><div className="anatomyVisual"><div className="birdSilhouette">{isCuts?'CUT':'ANATOMY'}</div><span>Original schematic learning visual</span></div><span className="tag">{sel[1]}</span><h2>{sel[0]}</h2><p>{sel[2]}</p><div className="detailCols"><div><b>Processing relevance</b><p>{sel[3]}</p></div><div><b>QC relevance</b><p>Use objective observations and approved plant criteria; escalate unusual findings according to procedure.</p></div></div></article></div></div>}
function Glossary(){const [q,setQ]=useState('');const terms=glossary.filter(x=>x[0].toLowerCase().includes(q.toLowerCase())||x[1].toLowerCase().includes(q.toLowerCase()));return <div className="content"><Crumb items={['Glossary']}/><PageHead eyebrow="A–Z REFERENCE" title="Glossary" text="Core poultry production, processing, QC and food-safety terminology."/><div className="glossSearch"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter terms…"/></div><div className="glossary">{terms.map(x=><article key={x[0]}><div className="letter">{x[0][0]}</div><div><h3>{x[0]}</h3><p>{x[1]}</p><span>Related: poultry • processing • QC</span></div></article>)}</div></div>}
function Sources(){return <div className="content"><Crumb items={['Sources & References']}/><PageHead eyebrow="SCIENTIFIC SOURCES" title="Sources & References" text="Use authoritative sources to verify technical and regulatory details. This atlas avoids presenting unverified numeric limits as universal rules."/><div className="sourceGrid">{[['FAO','Food and Agriculture Organization of the United Nations','Poultry production, animal health and food systems.','https://www.fao.org/'],['WOAH','World Organisation for Animal Health','Animal health, welfare and disease information.','https://www.woah.org/'],['USDA FSIS','Food Safety and Inspection Service','U.S. meat and poultry inspection and food-safety guidance.','https://www.fsis.usda.gov/'],['Codex Alimentarius','FAO/WHO food standards programme','International food standards and hygiene principles.','https://www.fao.org/fao-who-codexalimentarius/'],['EFSA','European Food Safety Authority','Scientific opinions on animal health, welfare and food safety.','https://www.efsa.europa.eu/']].map(x=><article className="sourceCard" key={x[0]}><span>AUTHORITY</span><h2>{x[0]}</h2><b>{x[1]}</b><p>{x[2]}</p><a href={x[3]} target="_blank" rel="noreferrer">Open official source ↗</a></article>)}</div><Callout title="Jurisdiction reminder">Requirements vary by jurisdiction. Verify against the applicable local regulation and plant procedures. Scientific and educational content here should not replace veterinary, regulatory or plant-specific direction.</Callout></div>}
function DamageAtlas(){const [cat,setCat]=useState('All');const cats=['All','Leg','Wing','Breast','Carcass','Processing'];const filtered=cat==='All'?defects:defects.filter(x=>x.toLowerCase().includes(cat.toLowerCase()));return <div className="content"><Crumb items={['Damage Atlas']}/><PageHead eyebrow="BROILER DAMAGE ATLAS" title="Damage Atlas" text="Use this reference to distinguish injury and processing damage from disease, normal anatomy and contamination."/><div className="filterRow"><Filter size={17}/>{cats.map(x=><button className={cat===x?'active':''} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className="damageGrid">{filtered.map((x,i)=><article key={x}><div className="damageVisual"><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b></div><span className="tag">Processing / injury reference</span><h3>{x}</h3><p><b>What it is:</b> An observable product condition requiring objective description.</p><p><b>Possible cause:</b> Consider catching, transport, equipment, process settings, handling or other contributing factors.</p><p><b>QC significance:</b> Trend recurrence and follow approved disposition/specification criteria.</p></article>)}</div><Callout title="Important distinction">Disease, processing damage, physiological variation and contamination are not interchangeable categories. When a finding could represent disease or a food-safety concern, follow veterinary and food-safety escalation procedures.</Callout></div>}
function DiseaseAtlas(){const data=[['Respiratory abnormality','Abnormality / veterinary concern','Observe respiratory signs or lesions and escalate according to veterinary procedure.'],['Lameness / abnormal gait','Abnormality / welfare','May indicate injury, skeletal or other health concerns; investigate flock-level patterns.'],['Organ abnormality','Abnormality','Unexpected organ appearance should be documented and escalated where appropriate.'],['Systemic illness concern','Disease concern','Do not diagnose from appearance alone; veterinary assessment may be required.']];return <div className="content"><Crumb items={['Disease & Abnormality Atlas']}/><PageHead eyebrow="DISEASE & ABNORMALITY ATLAS" title="Disease & Abnormality Atlas" text="A conservative training index. It intentionally avoids unsupported diagnosis and directs uncertain findings toward qualified veterinary review."/><div className="diseaseGrid">{data.map(x=><article key={x[0]}><div className="diseaseIcon"><AlertTriangle size={21}/></div><span className="tag">{x[1]}</span><h2>{x[0]}</h2><p>{x[2]}</p><h4>QC / food-safety relevance</h4><p>Document objective observations, segregate/control where required, and follow veterinary or food-safety escalation procedures.</p></article>)}</div><Callout title="No diagnosis from photos alone">Visual findings can overlap across disease, injury, physiological variation and processing defects. Use recognized veterinary references and competent professional assessment.</Callout></div>}
function Progress({progress}){const total=sections.flatMap(s=>s.items).length;const done=Object.keys(progress).length;return <div className="content"><Crumb items={['Progress']}/><PageHead eyebrow="YOUR LOCAL PROGRESS" title="Training Progress" text="Completion markers are stored locally in your browser. No account is required."/><div className="progressHero"><div className="ring"><b>{Math.min(100,Math.round(done/total*100))}%</b></div><div><h2>{done} items explored</h2><p>Continue through the sidebar or journey. Checklist and quiz states remain available during this session/device.</p></div></div><div className="completed">{Object.keys(progress).slice(0,30).map(x=><span key={x}><CheckCircle2 size={15}/>{x}</span>)}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
